CREATE TABLE materials_info
(MATERIAL_CODE varchar(100), MATERIAL_NAME varchar(100), MATERIAL_GROUP varchar(40), USE_FLAG varchar(40), CRT_DT datetime, UDT_DT datetime);


INSERT INTO dbo.materials_info VALUES ('A00', 'BATTERY_01', '배터리', 'Y', '2000-05-03', '2000-05-03');

SELECT * FROM materials_info;

/*  */

CREATE TABLE com_code
(CODE_ID varchar(10) PRIMARY KEY,
CODE_NAME varchar(100) NOT NULL, 
USE_FLAG  varchar(1) NOT NULL, 
CRT_DT datetime NOT NULL, 
UDT_DT datetime);

INSERT INTO com_code(CODE_ID, CODE_NAME, USE_FLAG, CRT_DT) VALUES 
('A', '배터리', 'Y', CURRENT_TIMESTAMP),
('B', '디스플레이', 'N', CURRENT_TIMESTAMP);

SELECT * FROM com_code;

SELECT CODE_ID FROM com_code;


INSERT INTO com_code(CODE_ID, CODE_NAME, USE_FLAG, CRT_DT) VALUES 
('C', '케이스', 'N', CURRENT_TIMESTAMP);



/*  */

SELECT MATERIAL_CODE, MATERIAL_NAME, MATERIAL_GROUP, USE_FLAG, CRT_DT, UDT_DT FROM materials_info WHERE MATERIAL_CODE = 'A00' OR MATERIAL_NAME = 'BATTERY_01'

SELECT MATERIAL.MATERIAL_CODE, MATERIAL.MATERIAL_NAME, CODE.CODE_NAME, CODE_ITEM.USE_FLAG, FORMAT(MATERIAL.CRT_DT, 'MM-dd') AS CRT_DT, FORMAT(MATERIAL.UDT_DT,'MM-dd') AS UDT_DT
FROM dbo.TB_COM_MATERIAL AS MATERIAL INNER JOIN dbo.TB_COM_CODE_ITEM AS CODE_ITEM
"ON MATERIAL.MATERIAL_CODE = CODE_ITEM.CODE_ITEM_ID " +
"INNER JOIN dbo.TB_COM_CODE AS CODE " +
"ON CODE.CODE_ID = CODE_ITEM.CODE_ID "



SELECT MI.MATERIAL_CODE, MI.MATERIAL_NAME, CC.CODE_NAME, CC.USE_FLAG, MT.CRT_DT, MT.UDT_DT
FROM materials_info AS MI INNER JOIN com_code AS CCi 
ON MI.MATERIAL_CODE = CC.CODE_ID


CREATE TABLE com_code_item
(CODE_ID varchar(10) PRIMARY KEY,
CODE_ITEM_ID varchar(100) F KEY, 
CODE_ITEM_NAME varchar(10) NOT NULL,
USE_FLAG  varchar(1) NOT NULL, 
CRT_DT datetime NOT NULL, 
UDT_DT datetime);
